# Kryptonim Stellar Integration
# SEP-1 Stellar Info File
# https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md

VERSION="2.7.0"

# Network Configuration
# Using Stellar Mainnet (Production)
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

# Stellar Accounts controlled by Kryptonim
ACCOUNTS=[
"GCA2HDG72UU5ZKGJAR3FWA33HJMFTQMJOVMVLTDO6IG6GEKIH2L5IOHL"
]

SIGNING_KEY="GBDPRI75CAWJHHK6IDPU5XLYDB4YA2FUJICAIV4QM4N6FZ7Q746JSFG4"

# Organization Documentation


# Primary Point of Contact
[[PRINCIPALS]]
